import { FormEvent, useCallback, useEffect, useMemo, useState } from 'react';
import { api, ApiError, BL, BLPage, Client, clearSession, Courier, getSession, login, Session, Summary } from './api';
import { BLDetail, ClientFinancials, Collections, CourierPerformance } from './Operations';

type Page = 'dashboard' | 'couriers' | 'clients' | 'bls' | 'collections' | 'financials' | 'performance';
const today = () => new Date().toISOString().slice(0, 10);
const euro = (value: string) => `${Number(value).toFixed(2)} €`;

function Loading() { return <div className="state">Chargement…</div>; }
function ErrorState({ message, retry }: { message: string; retry: () => void }) { return <div className="state error"><p>{message}</p><button onClick={retry}>Réessayer</button></div>; }
function Empty({ text }: { text: string }) { return <div className="state">{text}</div>; }

function Login({ onLogin }: { onLogin: (session: Session) => void }) {
  const [username, setUsername] = useState(''); const [password, setPassword] = useState(''); const [error, setError] = useState(''); const [pending, setPending] = useState(false);
  const submit = async (event: FormEvent) => { event.preventDefault(); setPending(true); setError(''); try { onLogin(await login(username, password)); } catch (err) { setError(err instanceof Error ? err.message : 'Connexion impossible.'); } finally { setPending(false); } };
  return <main className="login-shell"><form className="login-card" onSubmit={submit}><p className="eyebrow">MULTILENS GROUP</p><h1>BLTrack Admin</h1><p className="muted">Suivi des livraisons et encaissements.</p>{error && <p className="form-error">{error}</p>}<label>Nom d’utilisateur<input required value={username} onChange={(e) => setUsername(e.target.value)} autoComplete="username" /></label><label>Mot de passe<input required type="password" value={password} onChange={(e) => setPassword(e.target.value)} autoComplete="current-password" /></label><button className="primary" disabled={pending}>{pending ? 'Connexion…' : 'Se connecter'}</button></form></main>;
}

function Dashboard({ token }: { token: string }) {
  const [summary, setSummary] = useState<Summary | null>(null); const [recent, setRecent] = useState<BL[]>([]); const [error, setError] = useState('');
  const load = useCallback(async () => { setError(''); setSummary(null); try { const [nextSummary, recentPage] = await Promise.all([api<Summary>(`/api/dashboard/daily-summary?date=${today()}`, token), api<BLPage>('/api/bls?limit=5', token)]); setSummary(nextSummary); setRecent(recentPage.data); } catch (err) { setError(err instanceof Error ? err.message : 'Impossible de charger le tableau de bord.'); } }, [token]);
  useEffect(() => { void load(); }, [load]);
  if (error) return <ErrorState message={error} retry={() => void load()} />; if (!summary) return <Loading />;
  const cards = [['BL aujourd’hui', String(summary.totalBLs)], ['Total', euro(summary.totalAmount)], ['Espèces', euro(summary.cashAmount)], ['Chèques', euro(summary.chequeAmount)], ['En compte', euro(summary.accountAmount)], ['Payé', euro(summary.paidAmount)], ['En attente', euro(summary.pendingAmount)]];
  return <><section className="page-heading"><div><p className="eyebrow">VUE D’ENSEMBLE</p><h2>Activité du {summary.date}</h2></div><button onClick={() => void load()}>Actualiser</button></section><section className="metric-grid">{cards.map(([label, value]) => <article className="metric" key={label}><span>{label}</span><strong>{value}</strong></article>)}</section><section className="panel"><div className="panel-heading"><h3>BL récents</h3><span>{recent.length} affichés</span></div>{recent.length === 0 ? <Empty text="Aucun BL disponible." /> : <BLTable rows={recent} />}</section></>;
}

function Couriers({ token }: { token: string }) {
  const [data, setData] = useState<Courier[] | null>(null); const [error, setError] = useState(''); const load = useCallback(async () => { setData(null); setError(''); try { setData(await api<Courier[]>('/api/couriers', token)); } catch (err) { setError(err instanceof Error ? err.message : 'Impossible de charger les coursiers.'); } }, [token]); useEffect(() => { void load(); }, [load]);
  if (error) return <ErrorState message={error} retry={() => void load()} />; if (!data) return <Loading />; return <><section className="page-heading"><div><p className="eyebrow">ÉQUIPE</p><h2>Coursiers</h2></div><button onClick={() => void load()}>Actualiser</button></section><section className="panel">{data.length === 0 ? <Empty text="Aucun coursier actif." /> : <table><thead><tr><th>Nom</th><th>Identifiant</th><th>Statut</th></tr></thead><tbody>{data.map((courier) => <tr key={courier.id}><td>{courier.fullName}</td><td>{courier.username}</td><td><Status active={courier.isActive} /></td></tr>)}</tbody></table>}</section></>;
}

function Clients({ token }: { token: string }) {
  const [data, setData] = useState<Client[] | null>(null); const [error, setError] = useState(''); const load = useCallback(async () => { setData(null); setError(''); try { setData(await api<Client[]>('/api/clients', token)); } catch (err) { setError(err instanceof Error ? err.message : 'Impossible de charger les clients.'); } }, [token]); useEffect(() => { void load(); }, [load]);
  if (error) return <ErrorState message={error} retry={() => void load()} />; if (!data) return <Loading />; return <><section className="page-heading"><div><p className="eyebrow">RÉFÉRENTIEL</p><h2>Clients</h2></div><button onClick={() => void load()}>Actualiser</button></section><section className="panel">{data.length === 0 ? <Empty text="Aucun client disponible." /> : <table><thead><tr><th>Client</th><th>Type de règlement</th><th>Statut</th></tr></thead><tbody>{data.map((client) => <tr key={client.id}><td>{client.name}</td><td>{client.isAccountClient ? 'Compte' : 'Comptant'}</td><td><Status active={client.isActive} /></td></tr>)}</tbody></table>}</section></>;
}

function BLTable({ rows, onOpen }: { rows: BL[]; onOpen?: (id: string) => void }) { return <div className="table-wrap"><table><thead><tr><th>BL</th><th>Client</th><th>Coursier</th><th>Montant</th><th>Date</th><th>Règlement</th><th>Statut</th></tr></thead><tbody>{rows.map((bl) => <tr key={bl.id}><td className="strong">{onOpen ? <button className="link-button" onClick={() => onOpen(bl.id)}>{bl.blNumber}</button> : bl.blNumber}</td><td>{bl.client.name}</td><td>{bl.courier.fullName}</td><td>{euro(bl.amount)}</td><td>{new Date(bl.deliveryDate).toLocaleDateString()}</td><td><Method method={bl.paymentMethod} /></td><td><PaymentStatus status={bl.paymentStatus} /></td></tr>)}</tbody></table></div>; }
function Status({ active }: { active: boolean }) { return <span className={`pill ${active ? 'paid' : 'pending'}`}>{active ? 'Actif' : 'Inactif'}</span>; }
function Method({ method }: { method: BL['paymentMethod'] }) { return <span className="method">{method === 'CASH' ? 'Espèces' : method === 'CHEQUE' ? 'Chèque' : 'Compte'}</span>; }
function PaymentStatus({ status }: { status: BL['paymentStatus'] }) { return <span className={`pill ${status === 'PAID' ? 'paid' : 'pending'}`}>{status === 'PAID' ? 'Payé' : 'En attente'}</span>; }

function BLs({ token }: { token: string }) {
  const [data, setData] = useState<BLPage | null>(null); const [clients, setClients] = useState<Client[]>([]); const [couriers, setCouriers] = useState<Courier[]>([]); const [error, setError] = useState(''); const [detailId, setDetailId] = useState<string | null>(null); const [filters, setFilters] = useState({ date: '', courierId: '', clientId: '', paymentMethod: '', paymentStatus: '', page: 1 });
  const query = useMemo(() => { const params = new URLSearchParams({ page: String(filters.page), limit: '20' }); if (filters.date) { params.set('dateFrom', filters.date); params.set('dateTo', filters.date); } if (filters.courierId) params.set('courierId', filters.courierId); if (filters.clientId) params.set('clientId', filters.clientId); if (filters.paymentMethod) params.set('paymentMethod', filters.paymentMethod); if (filters.paymentStatus) params.set('paymentStatus', filters.paymentStatus); return params.toString(); }, [filters]);
  const load = useCallback(async () => { setData(null); setError(''); try { const [page, clientData, courierData] = await Promise.all([api<BLPage>(`/api/bls?${query}`, token), api<Client[]>('/api/clients', token), api<Courier[]>('/api/couriers', token)]); setData(page); setClients(clientData); setCouriers(courierData); } catch (err) { setError(err instanceof Error ? err.message : 'Impossible de charger les BL.'); } }, [query, token]); useEffect(() => { void load(); }, [load]);
  const update = (key: string, value: string) => setFilters((current) => ({ ...current, [key]: value, page: 1 }));
  if (detailId) return <BLDetail token={token} id={detailId} onBack={() => setDetailId(null)} />;
  if (error) return <ErrorState message={error} retry={() => void load()} />; if (!data) return <Loading />;
  return <><section className="page-heading"><div><p className="eyebrow">SUIVI DES LIVRAISONS</p><h2>BL et règlements</h2></div><button onClick={() => void load()}>Actualiser</button></section><section className="filters"><label>Date<input type="date" value={filters.date} onChange={(e) => update('date', e.target.value)} /></label><label>Coursier<select value={filters.courierId} onChange={(e) => update('courierId', e.target.value)}><option value="">Tous</option>{couriers.map((courier) => <option value={courier.id} key={courier.id}>{courier.fullName}</option>)}</select></label><label>Client<select value={filters.clientId} onChange={(e) => update('clientId', e.target.value)}><option value="">Tous</option>{clients.map((client) => <option value={client.id} key={client.id}>{client.name}</option>)}</select></label><label>Mode<select value={filters.paymentMethod} onChange={(e) => update('paymentMethod', e.target.value)}><option value="">Tous</option><option value="CASH">Espèces</option><option value="CHEQUE">Chèque</option><option value="ACCOUNT">Compte</option></select></label><label>Statut<select value={filters.paymentStatus} onChange={(e) => update('paymentStatus', e.target.value)}><option value="">Tous</option><option value="PAID">Payé</option><option value="PENDING">En attente</option></select></label></section><section className="panel">{data.data.length === 0 ? <Empty text="Aucun BL ne correspond aux filtres." /> : <BLTable rows={data.data} onOpen={setDetailId} />}<div className="pagination"><span>{data.pagination.total} BL</span><div><button disabled={data.pagination.page <= 1} onClick={() => setFilters((current) => ({ ...current, page: current.page - 1 }))}>Précédent</button><span>Page {data.pagination.page} / {Math.max(data.pagination.totalPages, 1)}</span><button disabled={data.pagination.page >= data.pagination.totalPages} onClick={() => setFilters((current) => ({ ...current, page: current.page + 1 }))}>Suivant</button></div></div></section></>;
}

export default function App() {
  const [session, setSession] = useState<Session | null>(() => { const saved = getSession(); return saved?.user.role === 'ADMIN' ? saved : null; }); const [page, setPage] = useState<Page>('dashboard');
  if (!session) return <Login onLogin={setSession} />;
  const logout = () => { clearSession(); setSession(null); };
  const content = page === 'dashboard' ? <Dashboard token={session.token} /> : page === 'couriers' ? <Couriers token={session.token} /> : page === 'clients' ? <Clients token={session.token} /> : page === 'collections' ? <Collections token={session.token} /> : page === 'financials' ? <ClientFinancials token={session.token} /> : page === 'performance' ? <CourierPerformance token={session.token} /> : <BLs token={session.token} />;
  return <div className="app-shell"><aside><div className="brand"><p className="eyebrow">MULTILENS GROUP</p><h1>BLTrack</h1><span>Administration</span></div><nav>{([['dashboard', 'Tableau de bord'], ['couriers', 'Coursiers'], ['clients', 'Clients'], ['bls', 'BL & règlements'], ['collections', 'Encaissements'], ['financials', 'Finances clients'], ['performance', 'Performance']] as [Page, string][]).map(([key, label]) => <button key={key} className={page === key ? 'active' : ''} onClick={() => setPage(key)}>{label}</button>)}</nav><div className="profile"><strong>{session.user.fullName}</strong><span>{session.user.username}</span><button onClick={logout}>Déconnexion</button></div></aside><main className="content"><header className="topbar"><span>Administration BLTrack</span><button className="mobile-logout" onClick={logout}>Déconnexion</button></header>{content}</main></div>;
}
