import { useCallback, useEffect, useState } from 'react';
import { api, BL, BLPage, CollectionPage, Financial, Performance } from './api';

const money = (value: number | string) => `${Number(value).toFixed(2)} €`;
const today = () => new Date().toISOString().slice(0, 10);
const rangeQuery = (from: string, to: string) => `?dateFrom=${from}&dateTo=${to}`;
const rangeFor = (preset: string) => {
  const end = new Date(); const start = new Date(end);
  if (preset === 'week') start.setDate(end.getDate() - 6);
  if (preset === 'month') start.setDate(end.getDate() - 29);
  const format = (value: Date) => value.toISOString().slice(0, 10);
  return { from: format(start), to: format(end) };
};
function State({ text, retry }: { text: string; retry?: () => void }) { return <div className="state"><p>{text}</p>{retry ? <button onClick={retry}>Réessayer</button> : null}</div>; }
function DateRange({ from, to, onChange }: { from: string; to: string; onChange: (from: string, to: string) => void }) { const preset = (value: string) => { const dates = rangeFor(value); onChange(dates.from, dates.to); }; return <div className="report-range"><button onClick={() => preset('today')}>Aujourd’hui</button><button onClick={() => preset('week')}>Cette semaine</button><button onClick={() => preset('month')}>Ce mois</button><label>Du<input type="date" value={from} onChange={(e) => onChange(e.target.value, to)} /></label><label>Au<input type="date" value={to} onChange={(e) => onChange(from, e.target.value)} /></label></div>; }
const Status = ({ value }: { value: string }) => <span className={`pill ${value === 'PAID' ? 'paid' : 'pending'}`}>{value === 'PAID' ? 'Payé' : 'En attente'}</span>;

export function BLDetail({ token, id, onBack }: { token: string; id: string; onBack: () => void }) { const [bl, setBL] = useState<BL | null>(null); const [error, setError] = useState(''); const load = useCallback(async () => { setBL(null); setError(''); try { setBL(await api<BL>(`/api/bls/${id}`, token)); } catch (err) { setError(err instanceof Error ? err.message : 'BL introuvable.'); } }, [id, token]); useEffect(() => { void load(); }, [load]); if (error) return <State text={error} retry={() => void load()} />; if (!bl) return <State text="Chargement du BL…" />; return <><section className="page-heading"><div><p className="eyebrow">DÉTAIL DU BL</p><h2>{bl.blNumber}</h2></div><button onClick={onBack}>Retour aux BL</button></section><section className="detail-grid"><article><span>Client</span><strong>{bl.client.name}</strong></article><article><span>Coursier</span><strong>{bl.courier.fullName}</strong></article><article><span>Montant</span><strong>{money(bl.amount)}</strong></article><article><span>Date de livraison</span><strong>{new Date(bl.deliveryDate).toLocaleString()}</strong></article><article><span>Mode de paiement</span><strong>{bl.paymentMethod}</strong></article><article><span>Statut</span><Status value={bl.paymentStatus} /></article><article className="wide"><span>Commentaire</span><strong>{bl.comments || 'Aucun commentaire'}</strong></article>{bl.createdAt ? <article><span>Créé le</span><strong>{new Date(bl.createdAt).toLocaleString()}</strong></article> : null}</section></>; }

export function Collections({ token }: { token: string }) { const [range, setRange] = useState(rangeFor('today')); const [data, setData] = useState<CollectionPage | null>(null); const [error, setError] = useState(''); const load = useCallback(async () => { setData(null); setError(''); try { setData(await api<CollectionPage>(`/api/reports/collections${rangeQuery(range.from, range.to)}`, token)); } catch (err) { setError(err instanceof Error ? err.message : 'Impossible de charger les encaissements.'); } }, [range, token]); useEffect(() => { void load(); }, [load]); const exportCsv = () => { if (!data) return; const rows = [['BL', 'Client', 'Coursier', 'Montant', 'Date', 'Mode', 'Statut'], ...data.data.map((bl) => [bl.blNumber, bl.client.name, bl.courier.fullName, bl.amount, bl.deliveryDate.slice(0, 10), bl.paymentMethod, bl.paymentStatus])]; const csv = `\uFEFF${rows.map((row) => row.map((cell) => `"${String(cell).replaceAll('"', '""')}"`).join(';')).join('\n')}`; const link = document.createElement('a'); link.href = URL.createObjectURL(new Blob([csv], { type: 'text/csv;charset=utf-8' })); link.download = `bltrack-encaissements-${range.from}-${range.to}.csv`; link.click(); URL.revokeObjectURL(link.href); }; if (error) return <State text={error} retry={() => void load()} />; if (!data) return <State text="Chargement des encaissements…" />; return <><section className="page-heading"><div><p className="eyebrow">ENCAISSEMENTS</p><h2>Collections en attente</h2></div><button onClick={exportCsv}>Exporter CSV</button></section><DateRange from={range.from} to={range.to} onChange={(from, to) => setRange({ from, to })} /><section className="metric-grid"><article className="metric"><span>Total outstanding</span><strong>{money(data.totalOutstanding)}</strong></article><article className="metric"><span>BL en attente</span><strong>{data.pagination.total}</strong></article></section><section className="panel">{data.data.length === 0 ? <State text="Aucun encaissement en attente pour cette période." /> : <table><thead><tr><th>BL</th><th>Client</th><th>Coursier</th><th>Montant</th><th>Date</th><th>Mode</th><th>Statut</th></tr></thead><tbody>{data.data.map((bl) => <tr key={bl.id}><td>{bl.blNumber}</td><td>{bl.client.name}</td><td>{bl.courier.fullName}</td><td>{money(bl.amount)}</td><td>{new Date(bl.deliveryDate).toLocaleDateString()}</td><td>{bl.paymentMethod}</td><td><Status value={bl.paymentStatus} /></td></tr>)}</tbody></table>}</section></>; }

export function ClientFinancials({ token }: { token: string }) { const [range, setRange] = useState(rangeFor('month')); const [data, setData] = useState<Financial[] | null>(null); const [history, setHistory] = useState<BLPage | null>(null); const [error, setError] = useState(''); const load = useCallback(async () => { setData(null); setError(''); try { setData(await api<Financial[]>(`/api/reports/client-financials${rangeQuery(range.from, range.to)}`, token)); } catch (err) { setError(err instanceof Error ? err.message : 'Impossible de charger la synthèse client.'); } }, [range, token]); useEffect(() => { void load(); }, [load]); const open = async (id: string) => { setHistory(null); try { setHistory(await api<BLPage>(`/api/bls?clientId=${id}&dateFrom=${range.from}&dateTo=${range.to}&limit=20`, token)); } catch { setError('Impossible de charger l’historique client.'); } }; if (error) return <State text={error} retry={() => void load()} />; if (!data) return <State text="Chargement des finances clients…" />; return <><section className="page-heading"><div><p className="eyebrow">CLIENTS</p><h2>Situation financière</h2></div></section><DateRange from={range.from} to={range.to} onChange={(from, to) => setRange({ from, to })} /><section className="panel"><table><thead><tr><th>Client</th><th>BL</th><th>Total</th><th>Payé</th><th>En attente</th></tr></thead><tbody>{data.map((entry) => <tr key={entry.client.id}><td><button className="link-button" onClick={() => void open(entry.client.id)}>{entry.client.name}</button></td><td>{entry.totalBLs}</td><td>{money(entry.totalAmount)}</td><td>{money(entry.paidAmount)}</td><td>{money(entry.pendingAmount)}</td></tr>)}</tbody></table></section>{history ? <section className="panel"><h3>Historique client</h3>{history.data.length === 0 ? <State text="Aucun BL pour cette période." /> : <table><thead><tr><th>BL</th><th>Montant</th><th>Date</th><th>Statut</th></tr></thead><tbody>{history.data.map((bl) => <tr key={bl.id}><td>{bl.blNumber}</td><td>{money(bl.amount)}</td><td>{new Date(bl.deliveryDate).toLocaleDateString()}</td><td><Status value={bl.paymentStatus} /></td></tr>)}</tbody></table>}</section> : null}</>; }

export function CourierPerformance({ token }: { token: string }) { const [range, setRange] = useState(rangeFor('month')); const [data, setData] = useState<Performance[] | null>(null); const [error, setError] = useState(''); const load = useCallback(async () => { setData(null); setError(''); try { setData(await api<Performance[]>(`/api/reports/courier-performance${rangeQuery(range.from, range.to)}`, token)); } catch (err) { setError(err instanceof Error ? err.message : 'Impossible de charger les performances.'); } }, [range, token]); useEffect(() => { void load(); }, [load]); if (error) return <State text={error} retry={() => void load()} />; if (!data) return <State text="Chargement des performances…" />; return <><section className="page-heading"><div><p className="eyebrow">COURIERS</p><h2>Performance</h2></div></section><DateRange from={range.from} to={range.to} onChange={(from, to) => setRange({ from, to })} /><section className="panel">{data.length === 0 ? <State text="Aucune activité pour cette période." /> : <table><thead><tr><th>Coursier</th><th>BL</th><th>Total</th><th>Espèces</th><th>Chèques</th><th>Compte</th><th>Payé</th><th>En attente</th></tr></thead><tbody>{data.map((entry) => <tr key={entry.courier.id}><td>{entry.courier.fullName}</td><td>{entry.totalBLs}</td><td>{money(entry.totalAmount)}</td><td>{money(entry.cashAmount)}</td><td>{money(entry.chequeAmount)}</td><td>{money(entry.accountAmount)}</td><td>{money(entry.paidAmount)}</td><td>{money(entry.pendingAmount)}</td></tr>)}</tbody></table>}</section></>; }
