import { useState } from 'react';
import { ScrollView, StyleSheet, Text, TextInput, TouchableOpacity } from 'react-native';
import { SafeAreaView } from 'react-native-safe-area-context';
import { useNavigation, useRoute, type RouteProp } from '@react-navigation/native';
import type { NativeStackNavigationProp } from '@react-navigation/native-stack';
import { RootStackParamList } from '../navigation/RootNavigator';
import { useCreateAvoir, useUpdateAvoir } from '../services/queries';
import { apiDate, colors, today } from '../utils/theme';

export function AvoirFormScreen() {
  const navigation = useNavigation<NativeStackNavigationProp<RootStackParamList>>(); const route = useRoute<RouteProp<RootStackParamList, 'AvoirForm'>>(); const existing = route.params.avoir; const create = useCreateAvoir(); const update = useUpdateAvoir();
  const [reference, setReference] = useState(existing?.brReference ?? ''); const [date, setDate] = useState(existing?.avoirDate.slice(0, 10) ?? today()); const [amount, setAmount] = useState(existing?.amount ?? ''); const [error, setError] = useState('');
  const submit = async () => { const value = Number(amount.replace(',', '.')); if (!reference.trim() || value <= 0 || !/^\d{4}-\d{2}-\d{2}$/.test(date)) return setError('Référence, date valide et montant positif sont requis.'); try { const payload = { brReference: reference.trim(), avoirDate: apiDate(date), amount: value }; if (existing) await update.mutateAsync({ blId: route.params.blId, avoirId: existing.id, payload }); else await create.mutateAsync({ blId: route.params.blId, payload }); navigation.goBack(); } catch (caught: unknown) { setError((caught as any)?.response?.data?.error?.message ?? 'Enregistrement impossible.'); } };
  return <SafeAreaView style={styles.safe}><ScrollView contentContainerStyle={styles.content}><TouchableOpacity onPress={() => navigation.goBack()}><Text style={styles.link}>‹ Annuler</Text></TouchableOpacity><Text style={styles.title}>{existing ? 'Modifier l’avoir' : 'Ajouter un avoir'}</Text><Text style={styles.note}>Le montant est saisi et stocké positif. Il sera affiché en négatif dans les rapports.</Text><Label text="Référence BR"/><TextInput style={styles.input} value={reference} onChangeText={setReference}/><Label text="Date avoir (AAAA-MM-JJ)"/><TextInput style={styles.input} value={date} onChangeText={setDate}/><Label text="Montant positif"/><TextInput style={styles.input} value={amount} onChangeText={setAmount} keyboardType="decimal-pad"/>{error ? <Text style={styles.error}>{error}</Text> : null}<TouchableOpacity style={styles.submit} onPress={() => void submit()}><Text style={styles.submitText}>Enregistrer l’avoir</Text></TouchableOpacity></ScrollView></SafeAreaView>;
}
function Label({ text }: { text: string }) { return <Text style={styles.label}>{text}</Text>; }
const styles = StyleSheet.create({ safe: { flex: 1, backgroundColor: colors.background }, content: { padding: 18 }, link: { color: colors.blueDark, fontWeight: '900' }, title: { color: colors.text, fontWeight: '900', fontSize: 28, marginTop: 24 }, note: { color: colors.muted, backgroundColor: colors.sky, padding: 13, borderRadius: 13, marginTop: 12, lineHeight: 19 }, scan: { borderWidth: 1, borderColor: colors.blue, borderRadius: 14, minHeight: 48, alignItems: 'center', justifyContent: 'center', marginTop: 16 }, scanText: { color: colors.blueDark, fontWeight: '900' }, label: { color: colors.text, fontWeight: '700', marginTop: 16, marginBottom: 7 }, input: { minHeight: 50, borderRadius: 14, borderWidth: 1, borderColor: colors.border, backgroundColor: colors.card, paddingHorizontal: 14 }, error: { color: colors.red, marginTop: 12 }, submit: { backgroundColor: colors.blueDark, borderRadius: 16, minHeight: 54, alignItems: 'center', justifyContent: 'center', marginTop: 20 }, submitText: { color: 'white', fontWeight: '900' } });
