import { useEffect, useState } from 'react';
import { ActivityIndicator, ScrollView, StyleSheet, Text, TextInput, TouchableOpacity } from 'react-native';
import { SafeAreaView } from 'react-native-safe-area-context';
import { useNavigation, useRoute, type RouteProp } from '@react-navigation/native';
import type { NativeStackNavigationProp } from '@react-navigation/native-stack';
import { RootStackParamList } from '../navigation/RootNavigator';
import { useBL, useClients, useUpdateBL } from '../services/queries';
import { apiDate, colors } from '../utils/theme';

export function EditBLScreen() {
  const navigation = useNavigation<NativeStackNavigationProp<RootStackParamList>>(); const route = useRoute<RouteProp<RootStackParamList, 'EditBL'>>(); const query = useBL(route.params.blId); const clients = useClients(); const update = useUpdateBL();
  const [number, setNumber] = useState(''); const [clientId, setClientId] = useState(''); const [date, setDate] = useState(''); const [amount, setAmount] = useState(''); const [comments, setComments] = useState(''); const [error, setError] = useState('');
  useEffect(() => { if (query.data) { setNumber(query.data.blNumber); setClientId(query.data.client.id); setDate(query.data.blDate.slice(0, 10)); setAmount(query.data.amount); setComments(query.data.comments ?? ''); } }, [query.data]);
  const submit = async () => { const value = Number(amount.replace(',', '.')); if (!number.trim() || !clientId || value <= 0 || !/^\d{4}-\d{2}-\d{2}$/.test(date)) return setError('Vérifiez les champs obligatoires.'); try { await update.mutateAsync({ id: route.params.blId, blNumber: number.trim(), clientId, amount: value, blDate: apiDate(date), comments: comments.trim() || undefined }); navigation.goBack(); } catch (caught: unknown) { setError((caught as any)?.response?.data?.error?.message ?? 'Modification impossible.'); } };
  if (query.isLoading) return <SafeAreaView style={styles.center}><ActivityIndicator/></SafeAreaView>;
  return <SafeAreaView style={styles.safe}><ScrollView contentContainerStyle={styles.content}><TouchableOpacity onPress={() => navigation.goBack()}><Text style={styles.link}>‹ Annuler</Text></TouchableOpacity><Text style={styles.title}>Modifier le BL</Text><Label text="Numéro BL"/><TextInput style={styles.input} value={number} onChangeText={setNumber}/><Label text="Client"/><ScrollView horizontal contentContainerStyle={styles.choices}>{(clients.data ?? []).filter(c => c.isActive).map(c => <TouchableOpacity key={c.id} style={[styles.choice, clientId === c.id && styles.selected]} onPress={() => setClientId(c.id)}><Text style={[styles.choiceText, clientId === c.id && styles.selectedText]}>{c.name}</Text></TouchableOpacity>)}</ScrollView><Label text="Date BL"/><TextInput style={styles.input} value={date} onChangeText={setDate}/><Label text="Montant BL"/><TextInput style={styles.input} value={amount} onChangeText={setAmount} keyboardType="decimal-pad"/><Label text="Commentaire"/><TextInput style={[styles.input, styles.area]} value={comments} onChangeText={setComments} multiline/>{error ? <Text style={styles.error}>{error}</Text> : null}<TouchableOpacity style={styles.submit} disabled={update.isPending} onPress={() => void submit()}><Text style={styles.submitText}>{update.isPending ? 'Enregistrement…' : 'Enregistrer'}</Text></TouchableOpacity></ScrollView></SafeAreaView>;
}
function Label({ text }: { text: string }) { return <Text style={styles.label}>{text}</Text>; }
const styles = StyleSheet.create({ safe: { flex: 1, backgroundColor: colors.background }, center: { flex: 1, justifyContent: 'center' }, content: { padding: 18, paddingBottom: 40 }, link: { color: colors.blueDark, fontWeight: '900' }, title: { color: colors.text, fontSize: 28, fontWeight: '900', marginTop: 24 }, label: { color: colors.text, fontWeight: '700', marginTop: 16, marginBottom: 7 }, input: { minHeight: 50, borderRadius: 14, borderWidth: 1, borderColor: colors.border, backgroundColor: colors.card, paddingHorizontal: 14 }, area: { minHeight: 85, textAlignVertical: 'top', paddingTop: 12 }, choices: { gap: 8 }, choice: { padding: 11, borderRadius: 16, backgroundColor: colors.card, borderWidth: 1, borderColor: colors.border }, selected: { backgroundColor: colors.navy }, choiceText: { color: colors.text, fontWeight: '700' }, selectedText: { color: 'white' }, submit: { minHeight: 54, backgroundColor: colors.blueDark, borderRadius: 16, alignItems: 'center', justifyContent: 'center', marginTop: 20 }, submitText: { color: 'white', fontWeight: '900' }, error: { color: colors.red, marginTop: 12 } });
