import { useEffect, useState } from 'react';
import { ActivityIndicator, StyleSheet, Text, TouchableOpacity, View } from 'react-native';
import { SafeAreaView } from 'react-native-safe-area-context';
import { useNavigation, useRoute, type RouteProp } from '@react-navigation/native';
import type { NativeStackNavigationProp } from '@react-navigation/native-stack';
import { RootStackParamList } from '../navigation/RootNavigator';
import { useBL, useRegisterPayment } from '../services/queries';
import type { PaymentMethod } from '../types';
import { colors, formatDH } from '../utils/theme';

export function PaymentScreen() {
  const navigation = useNavigation<NativeStackNavigationProp<RootStackParamList>>(); const route = useRoute<RouteProp<RootStackParamList, 'Payment'>>(); const query = useBL(route.params.blId); const payment = useRegisterPayment(); const [method, setMethod] = useState<PaymentMethod>(query.data?.payment?.method ?? 'CASH'); const [error, setError] = useState('');
  useEffect(() => { if (query.data?.payment?.method) setMethod(query.data.payment.method); }, [query.data?.payment?.method]);
  const submit = async () => { if (!query.data) return; try { await payment.mutateAsync({ blId: query.data.id, amount: Number(query.data.netAmount), status: 'PAID', method }); navigation.goBack(); } catch (caught: unknown) { setError((caught as any)?.response?.data?.error?.message ?? 'Paiement impossible.'); } };
  if (query.isLoading || !query.data) return <SafeAreaView style={styles.center}><ActivityIndicator/></SafeAreaView>; const bl = query.data;
  const hasHistoricalDifference = bl.payment?.status === 'PAID' && Number(bl.paymentDifferenceAmount) !== 0;
  const difference = Number(bl.paymentDifferenceAmount);
  return <SafeAreaView style={styles.safe}><TouchableOpacity onPress={() => navigation.goBack()}><Text style={styles.link}>‹ Annuler</Text></TouchableOpacity><Text style={styles.title}>Paiement du BL</Text><Text style={styles.number}>{bl.blNumber} · {bl.client.name}</Text><View style={styles.amount}><Text style={styles.muted}>{hasHistoricalDifference ? 'Montant payé historique' : 'Montant net à régler'}</Text><Text style={styles.amountValue}>{formatDH(hasHistoricalDifference ? bl.paidAmount ?? 0 : bl.netAmount)}</Text></View>{hasHistoricalDifference ? <Text style={styles.account}>Le paiement historique et sa date sont conservés. {difference > 0 ? `Surpaiement actuel : +${formatDH(difference)}` : `Écart paiement / net : ${formatDH(difference)}`}.</Text> : bl.payment?.status === 'EN_COMPTE' ? <Text style={styles.account}>Ce BL est EN COMPTE : aucun mode ni date de paiement ne peut être enregistré.</Text> : <><Text style={styles.label}>Mode de paiement</Text><View style={styles.methods}>{(['CASH', 'CHEQUE'] as PaymentMethod[]).map(value => <TouchableOpacity key={value} style={[styles.method, method === value && styles.selected]} onPress={() => setMethod(value)}><Text style={[styles.methodText, method === value && styles.selectedText]}>{value === 'CASH' ? 'Espèces' : 'Chèque'}</Text></TouchableOpacity>)}</View><Text style={styles.note}>La date de paiement sera enregistrée par le serveur au moment de la validation.</Text>{error ? <Text style={styles.error}>{error}</Text> : null}<TouchableOpacity style={styles.submit} disabled={payment.isPending} onPress={() => void submit()}><Text style={styles.submitText}>{payment.isPending ? 'Validation…' : bl.payment?.status === 'PAID' ? 'Mettre à jour le paiement' : 'Confirmer le paiement'}</Text></TouchableOpacity></>}</SafeAreaView>;
}
const styles = StyleSheet.create({ safe: { flex: 1, padding: 18, backgroundColor: colors.background }, center: { flex: 1, justifyContent: 'center' }, link: { color: colors.blueDark, fontWeight: '900' }, title: { color: colors.text, fontWeight: '900', fontSize: 28, marginTop: 25 }, number: { color: colors.muted, marginTop: 5 }, amount: { backgroundColor: colors.card, borderWidth: 1, borderColor: colors.border, borderRadius: 18, padding: 18, marginTop: 24 }, muted: { color: colors.muted }, amountValue: { color: colors.blueDark, fontWeight: '900', fontSize: 30, marginTop: 7 }, label: { color: colors.text, fontWeight: '800', marginTop: 25 }, methods: { flexDirection: 'row', gap: 10, marginTop: 10 }, method: { flex: 1, minHeight: 54, alignItems: 'center', justifyContent: 'center', borderRadius: 15, borderWidth: 1, borderColor: colors.border, backgroundColor: colors.card }, selected: { backgroundColor: colors.navy }, methodText: { color: colors.text, fontWeight: '800' }, selectedText: { color: 'white' }, note: { color: colors.muted, lineHeight: 19, marginTop: 14 }, account: { color: colors.account, backgroundColor: '#F0EDFF', padding: 15, borderRadius: 14, marginTop: 24, lineHeight: 20 }, error: { color: colors.red, marginTop: 12 }, submit: { backgroundColor: colors.blueDark, borderRadius: 16, minHeight: 54, alignItems: 'center', justifyContent: 'center', marginTop: 22 }, submitText: { color: 'white', fontWeight: '900' } });
