import { useState } from 'react';
import { ActivityIndicator, ScrollView, StyleSheet, Text, TextInput, TouchableOpacity, View } from 'react-native';
import { SafeAreaView } from 'react-native-safe-area-context';
import { BottomNav } from '../components/BottomNav';
import { useAuth } from '../services/auth';
import { useAvoirReport, useBLReport } from '../services/queries';
import { paymentLabel } from '../utils/domain';
import { colors, formatDate, formatDH, today } from '../utils/theme';

type Tab = 'BL' | 'AVOIR';
export function ReportsScreen() {
  const { user } = useAuth(); const [tab, setTab] = useState<Tab>('BL'); const [fromInput, setFromInput] = useState(today()); const [toInput, setToInput] = useState(today()); const [range, setRange] = useState({ from: today(), to: today() }); const [error, setError] = useState('');
  const bl = useBLReport(range.from, range.to); const avoir = useAvoirReport(range.from, range.to);
  const apply = () => { if (!/^\d{4}-\d{2}-\d{2}$/.test(fromInput) || !/^\d{4}-\d{2}-\d{2}$/.test(toInput) || fromInput > toInput) return setError('La période est invalide.'); setError(''); setRange({ from: fromInput, to: toInput }); };
  return <SafeAreaView style={styles.safe} edges={['top']}><View style={styles.page}><ScrollView contentContainerStyle={styles.content}><Text style={styles.title}>Rapports</Text><View style={styles.tabs}>{(['BL', 'AVOIR'] as Tab[]).map(value => <TouchableOpacity key={value} style={[styles.tab, tab === value && styles.tabActive]} onPress={() => setTab(value)}><Text style={[styles.tabText, tab === value && styles.tabTextActive]}>Rapport {value === 'BL' ? 'BL' : 'Avoir'}</Text></TouchableOpacity>)}</View><View style={styles.range}><View style={styles.dateBox}><Text style={styles.small}>Du</Text><TextInput style={styles.dateInput} value={fromInput} onChangeText={setFromInput}/></View><View style={styles.dateBox}><Text style={styles.small}>Au</Text><TextInput style={styles.dateInput} value={toInput} onChangeText={setToInput}/></View></View>{error ? <Text style={styles.error}>{error}</Text> : null}<TouchableOpacity style={styles.apply} onPress={apply}><Text style={styles.applyText}>Générer</Text></TouchableOpacity>
    <View style={styles.document}><Text style={styles.brand}>BLTrack</Text><Text style={styles.docTitle}>Rapport {tab === 'BL' ? 'des bons de livraison' : 'des avoirs'}</Text><Text style={styles.meta}>Période : {range.from} → {range.to}</Text><Text style={styles.meta}>Coursier : {user?.fullName ?? '—'}</Text><Text style={styles.printNote}>Aperçu prêt pour impression / export PDF.</Text>
      {tab === 'BL' ? <BLDocument query={bl}/> : <AvoirDocument query={avoir}/>}</View></ScrollView></View><BottomNav active="Reports" /></SafeAreaView>;
}
function BLDocument({ query }: { query: ReturnType<typeof useBLReport> }) { if (query.isLoading) return <ActivityIndicator/>; if (query.isError) return <Text style={styles.error}>Rapport indisponible.</Text>; return <>{query.data?.data.map(row => <View style={styles.reportRow} key={row.id}><View style={styles.rowTop}><Text style={styles.rowTitle}>{row.blNumber}</Text><Text style={styles.rowAmount}>{formatDH(row.blAmount)}</Text></View><Text style={styles.rowText}>{row.client.name} · BL {formatDate(row.blDate)}</Text><Text style={styles.rowText}>Avoir : −{formatDH(row.avoirTotal)} · Net : {formatDH(row.netAmount)}</Text><Text style={styles.rowText}>{paymentLabel(row.paymentStatus ?? 'UNPAID')}{row.paymentMethod ? ` · ${row.paymentMethod === 'CASH' ? 'Espèces' : 'Chèque'}` : ''}{row.paidAt ? ` · ${formatDate(row.paidAt)}` : ''}</Text>{row.paidAmount !== null ? <Text style={styles.rowText}>Payé : {formatDH(row.paidAmount)} · {Number(row.paymentDifferenceAmount) > 0 ? 'Surpaiement' : 'Écart'} : {Number(row.paymentDifferenceAmount) > 0 ? '+' : ''}{formatDH(row.paymentDifferenceAmount ?? 0)}</Text> : null}<Text style={styles.rowText}>Coursier : {row.user.fullName}</Text></View>)}<View style={styles.total}><Text style={styles.totalText}>Total montant BL</Text><Text style={styles.totalValue}>{formatDH(query.data?.totalBLAmount ?? 0)}</Text></View>{!query.data?.data.length ? <Text style={styles.empty}>Aucune activité BL dans la période.</Text> : null}</>; }
function AvoirDocument({ query }: { query: ReturnType<typeof useAvoirReport> }) { if (query.isLoading) return <ActivityIndicator/>; if (query.isError) return <Text style={styles.error}>Rapport indisponible.</Text>; return <>{query.data?.data.map(row => <View style={styles.reportRow} key={row.id}><View style={styles.rowTop}><Text style={styles.rowTitle}>{row.brReference}</Text><Text style={styles.credit}>−{formatDH(row.avoirAmount)}</Text></View><Text style={styles.rowText}>{row.bl.blNumber} · {row.client.name}</Text><Text style={styles.rowText}>Date avoir : {formatDate(row.avoirDate)}</Text><Text style={styles.rowText}>Coursier : {row.user.fullName}</Text></View>)}<View style={styles.total}><Text style={styles.totalText}>Total avoir</Text><Text style={styles.credit}>−{formatDH(query.data?.totalAvoirAmount ?? 0)}</Text></View>{!query.data?.data.length ? <Text style={styles.empty}>Aucun avoir dans la période.</Text> : null}</>; }
const styles = StyleSheet.create({ safe: { flex: 1, backgroundColor: colors.background }, page: { flex: 1 }, content: { padding: 16, paddingBottom: 100 }, title: { color: colors.text, fontSize: 28, fontWeight: '900' }, tabs: { flexDirection: 'row', backgroundColor: '#E8EDF2', padding: 4, borderRadius: 14, marginTop: 16 }, tab: { flex: 1, minHeight: 43, alignItems: 'center', justifyContent: 'center', borderRadius: 11 }, tabActive: { backgroundColor: colors.card }, tabText: { color: colors.muted, fontWeight: '800' }, tabTextActive: { color: colors.text }, range: { flexDirection: 'row', gap: 10, marginTop: 15 }, dateBox: { flex: 1 }, small: { color: colors.muted, fontSize: 11, marginBottom: 4 }, dateInput: { backgroundColor: colors.card, borderWidth: 1, borderColor: colors.border, borderRadius: 12, padding: 11, color: colors.text }, apply: { backgroundColor: colors.blueDark, borderRadius: 14, minHeight: 48, alignItems: 'center', justifyContent: 'center', marginTop: 12 }, applyText: { color: 'white', fontWeight: '900' }, error: { color: colors.red, marginTop: 10 }, document: { backgroundColor: colors.card, borderWidth: 1, borderColor: colors.border, borderRadius: 18, padding: 16, marginTop: 18 }, brand: { color: colors.blueDark, fontSize: 14, fontWeight: '900', letterSpacing: 1 }, docTitle: { color: colors.text, fontSize: 21, fontWeight: '900', marginTop: 5 }, meta: { color: colors.muted, marginTop: 3, fontSize: 12 }, printNote: { color: colors.blueDark, backgroundColor: colors.sky, borderRadius: 9, padding: 9, marginTop: 12, fontSize: 11 }, reportRow: { borderTopWidth: 1, borderTopColor: colors.border, paddingVertical: 13 }, rowTop: { flexDirection: 'row', justifyContent: 'space-between' }, rowTitle: { color: colors.text, fontWeight: '900' }, rowAmount: { color: colors.text, fontWeight: '900' }, rowText: { color: colors.muted, fontSize: 12, marginTop: 4 }, credit: { color: colors.red, fontWeight: '900' }, total: { flexDirection: 'row', justifyContent: 'space-between', borderTopWidth: 2, borderTopColor: colors.navy, paddingTop: 13 }, totalText: { color: colors.text, fontWeight: '900' }, totalValue: { color: colors.blueDark, fontWeight: '900' }, empty: { color: colors.muted, textAlign: 'center', padding: 18 } });
